baseurl: ""

title: The Bond Cellar - Expert in Bond Origination & Home Loans in the Western Cape
email: mailto:admin@thebondcellar.co.za
description: "Need help securing your home loan in Cape Town? The Bond Cellar is a trusted bond origination specialist serving clients across the Western Cape. We simplify the mortgage process by comparing offers from multiple lenders, handling paperwork, and fighting for your best interest rate. Whether you're buying your first home, investing in property, or refinancing, we guide you through every stepâ€”from pre-approval to keys in hand. Our team knows the local market inside out and works directly with major banks to get your bond approved faster."
author: Eben Roux / Pieter Oosthuizen

analytics:
  google: G-XXX

collections:
  portfolio:

markdown: kramdown

webserver_headers:
  - - Access-Control-Allow-Origin
    - "*"
  - - Access-Control-Allow-Methods
    - GET, OPTIONS, HEAD

logo:
  path: /assets/img/logo/the-bond-cellar-logo.jpg

exclude: [node_modules, webpack-config.js, package.json, package-lock.json]

group: The Bond Cellar

company: The Bond Cellar

url: https://evohomeloans.co.za

address:
